import React from 'react'
import styled from 'styled-components'
import { useHistory } from 'react-router-dom'
import { Flex } from '@rebass/grid'
import { MainButton } from '../styles/Button'
import { setFont } from '../utils/styles'
import OnboardingSlide from './OnboardingSlide'
import { useMutation } from '@apollo/react-hooks'
import { CreateCampaign } from '../__generated__/CreateCampaign'
import { CREATE_CAMPAIGN } from '../pages/CampaignsList'

const landingIllustration = require('../images/illustrations/landing.png')
const campaignIllustration = require('../images/illustrations/campaign.svg')
const propositionsIllustration = require('../images/illustrations/propositions.svg')
const performancesIllustration = require('../images/illustrations/performances.svg')

const Title = styled.p`
  ${setFont(600, 'huge')}
  max-width: 20em;
  line-height: 1.2em;
`

const FullPage = styled(Flex)`
  @media screen and (min-width: ${props => props.theme.breakpoints[0]}) {
    height: calc(100vh - 70px);
    padding-top: 0;
    padding-bottom: 0;
  }

  main {
    height: 100%;
    padding-right: 2rem;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: flex-start;

    p.pitch {
      margin-top: 20px;
      margin-bottom: 10px;
      max-width: 500px;
    }
  }

  img.landing {
    width: 550px;
    height: auto;
    align-self: center;
    @media screen and (max-width: ${props => props.theme.breakpoints[0]}) {
      display: none;
    }
  }
`

interface ISlidesState {
  step: 'intro' | 'slides'
  slide: number
}

const initialSlidesState: ISlidesState = {
  step: 'slides',
  slide: 0,
}

const slidesReducer = (
  state: ISlidesState,
  action: 'NEXT_SLIDE' | 'START_SLIDES'
): ISlidesState => {
  switch (action) {
    case 'START_SLIDES':
      return {
        step: 'slides',
        slide: 0,
      }
    case 'NEXT_SLIDE':
      return {
        ...state,
        slide: state.slide + 1,
      }
    default:
      return state
  }
}

const BrandOnboarding: React.FC<{}> = () => {
  const history = useHistory()
  const [createCampaign] = useMutation<CreateCampaign>(CREATE_CAMPAIGN, {
    onCompleted: ({ createCampaign: { _id } }) => {
      history.push(`/brand/campaigns/${_id}/brief`)
    },
  })
  // Store current status in state
  const [slidesState, slidesDispatch] = React.useReducer(slidesReducer, initialSlidesState)

  // Slides data
  const slides = [
    {
      title: 'Create your campaign',
      description:
        'Take 2 minutes to fill your campaign brief. It will be shown to more than 2k streamers.',
      buttonText: 'Next step',
      handleButtonClick: () => slidesDispatch('NEXT_SLIDE'),
      image: campaignIllustration,
    },
    {
      title: 'Receive collab requests',
      description:
        'Receive requests from influencers who want to try your product. You can check their audience insights (country, age...) to choose the best profiles',
      buttonText: 'Next step',
      handleButtonClick: () => slidesDispatch('NEXT_SLIDE'),
      image: propositionsIllustration,
    },
    {
      title: 'Measure your performances',
      description:
        'Check the engagement generated by your campaigns (likes, comments, impressions…)',
      buttonText: 'Create my campaign',
      handleButtonClick: () => createCampaign(),
      image: performancesIllustration,
    },
  ]

  // Onboarding slides
  return <OnboardingSlide {...slides[slidesState.slide]} index={slidesState.slide + 1} />
}

export default BrandOnboarding
